### ISSUE TITLE
`--find-links` in `requirements.txt` not handled

### ISSUE THREAD

**Issue by fviernau** [nexB/python-inspector#142]
For example, the library `torch==2.0.0+cpu` is not on [pypi](https://pypi.org/).
It can however be installed by passing an URL pointing to an HTML page via `--find-links to `pip`.

This can be done inside a `requirements.txt` as follows:

```
-f https://download.pytorch.org/whl/cpu/torch_stable.html
torch==2.0.0+cpu
```

So, for above `requirements.txt`, python inspector is unable to "resolve" the dependencies.

**Comment by fviernau** [comment]
I've meanwhile found that there is supported implemented for `--extra-index-url`[1].
So, as a work around I tried this requirements file:
```
--index-url https://download.pytorch.org/whl/cpu
torch==2.0.0+cpu
```

This can be successfully obtained with pip (and python 3.10), but not with `python-inspector` [2].

[1] https://github.com/nexB/python-inspector/commit/b66aa71660f93b5b1994a747dd5f002f157b512a
[2] 
```
python-inspector -p 3.10  --operating-system linux --json-pdt x.json --analyze-setup-py-insecurely --requirement requirements.txt --verbose
Resolving dependencies...
direct_dependencies:
 DependentPackage(purl='pkg:pypi/torch@2.0.0%2Bcpu', extracted_requirement='torch==2.0.0+cpu', scope='install')
environment: Environment(python_version='310', operating_system='linux')
repos:
 PypiSimpleRepository(index_url='https://pypi.org/simple', credentials=None)
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/frank/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: <Requirement('torch==2.0.0+cpu')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/python_inspector/resolve_cli.py", line 247, in resolve_dependencies
    resolution_result: Dict = resolver_api(
  File "/home/frank/.local/lib/python3.10/site-packages/python_inspector/api.py", line 263, in resolve_dependencies
    resolution, purls = resolve(
  File "/home/frank/.local/lib/python3.10/site-packages/python_inspector/api.py", line 322, in resolve
    resolved_dependencies, packages = get_resolved_dependencies(
  File "/home/frank/.local/lib/python3.10/site-packages/python_inspector/api.py", line 360, in get_resolved_dependencies
    resolver_results = resolver.resolve(requirements=requirements, max_rounds=max_rounds)
  File "/home/frank/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/frank/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=<Requirement('torch==2.0.0+cpu')>, parent=None)]
```
