### ISSUE TITLE
Failed to resolve scancode-toolkit

### ISSUE THREAD

**Issue by pombredanne** [nexB/python-inspector#34]
Using the latest at https://github.com/nexB/python-inspector/tree/9ae28749938603b740206ca67a49f1421252e361  I get this:
```shell
$ dad --specifier scancode-toolkit --json -
Resolving dependencies...
Traceback (most recent call last):
  File "/tmp/python-inspector/venv/bin/dad", line 33, in <module>
    sys.exit(load_entry_point('python-inspector', 'console_scripts', 'dad')())
  File "/tmp/python-inspector/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/python-inspector/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/tmp/python-inspector/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/python-inspector/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/python-inspector/src/python_inspector/resolve_cli.py", line 194, in resolve_dependencies
    requirements, resolved_dependencies = resolve(
  File "/tmp/python-inspector/src/python_inspector/resolve_cli.py", line 247, in resolve
    resolved_dependencies = get_resolved_dependencies(
  File "/tmp/python-inspector/src/python_inspector/resolution.py", line 329, in get_resolved_dependencies
    results = resolver.resolve(requirements=requirements)
  File "/tmp/python-inspector/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/tmp/python-inspector/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 385, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=<Requirement('intbitset<3.0,>=2.3.0')>, parent=Candidate(name='scancode-toolkit', version=<Version('30.1.0')>, extras=set())), RequirementInformation(requirement=<Requirement('intbitset<3.0,>=2.3.0')>, parent=Candidate(name='scancode-toolkit', version=<Version('30.0.1')>, extras=set())), RequirementInformation(requirement=<Requirement('intbitset<3.0,>=2.3.0')>, parent=Candidate(name='scancode-toolkit', version=<Version('30.0.0')>, extras=set())), RequirementInformation(requirement=<Requirement('intbitset<3.0,>=2.3.0')>, parent=Candidate(name='scancode-toolkit', version=<Version('21.8.4')>, extras=set())), RequirementInformation(requirement=<Requirement('intbitset<3.0,>=2.3.0')>, parent=Candidate(name='scancode-toolkit', version=<Version('21.7.30')>, extras=set())), RequirementInformation(requirement=<Requirement('intbitset<3.0,>=2.3.0')>, parent=Candidate(name='scancode-toolkit', version=<Version('21.6.7')>, extras=set())), RequirementInformation(requirement=<Requirement('bitarray<1.0.0,>=0.8.1')>, parent=Candidate(name='scancode-toolkit', version=<Version('21.3.31')>, extras=set())), RequirementInformation(requirement=<Requirement('bitarray<1.0.0,>=0.8.1')>, parent=Candidate(name='scancode-toolkit', version=<Version('21.2.25')>, extras=set())), RequirementInformation(requirement=<Requirement('bitarray<1.0.0,>=0.8.1')>, parent=Candidate(name='scancode-toolkit', version=<Version('21.2.9')>, extras=set())), RequirementInformation(requirement=<Requirement('future>=0.16.0')>, parent=Candidate(name='scancode-toolkit', version=<Version('3.2.3')>, extras=set())), RequirementInformation(requirement=<Requirement('patch<1.20,>=1.15')>, parent=Candidate(name='scancode-toolkit', version=<Version('3.2.0')>, extras=set())), RequirementInformation(requirement=<Requirement('patch<1.20,>=1.15')>, parent=Candidate(name='scancode-toolkit', version=<Version('3.1.1')>, extras=set()))]
```

**Comment by TG1999** [comment]
@pombredanne I wasn't able to reproduce this error, here is the result json file
[sc.json.txt](https://github.com/nexB/python-inspector/files/9149175/sc.json.txt)

**Comment by pombredanne** [comment]
Never mind... I was mistakenly running from an other, older branch than main.
