### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by tdruez** [nexB/python-inspector#48]
```
$ pip install git+https://github.com/nexB/python-inspector
$ dad --requirement requirement.txt --json -
```

Output:
```
Traceback (most recent call last):
  File "python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "python3.9/site-packages/python_inspector/resolve_cli.py", line 233, in resolve_dependencies
    requirements, resolved_dependencies = resolve(
  File "python3.9/site-packages/python_inspector/resolve_cli.py", line 291, in resolve
    resolved_dependencies = get_resolved_dependencies(
  File "python3.9/site-packages/python_inspector/resolution.py", line 530, in get_resolved_dependencies
    results = resolver.resolve(requirements=requirements, max_rounds=max_rounds)
  File "python3.9/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "python3.9/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "python3.9/site-packages/resolvelib/resolvers.py", line 147, in _add_to_criteria
    matches = self._p.find_matches(
  File "python3.9/site-packages/python_inspector/resolution.py", line 340, in find_matches
    candidates = sorted(
  File "python3.9/site-packages/python_inspector/resolution.py", line 333, in _iter_matches
    all_versions = self.get_versions_for_package(name, repo)
  File "python3.9/site-packages/python_inspector/resolution.py", line 163, in get_versions_for_package
    return self.get_versions_for_package_from_repo(name, repo)
  File "python3.9/site-packages/python_inspector/resolution.py", line 172, in get_versions_for_package_from_repo
    for version, package in repo.get_package_versions(name).items():
  File "python3.9/site-packages/python_inspector/utils_pypi.py", line 1515, in get_package_versions
    self._get_package_versions_map(
  File "python3.9/site-packages/python_inspector/utils_pypi.py", line 1483, in _get_package_versions_map
    links = self.fetch_links(
  File "python3.9/site-packages/python_inspector/utils_pypi.py", line 1561, in fetch_links
    text = CACHE.get(
  File "python3.9/site-packages/python_inspector/utils_pypi.py", line 1626, in get
    content = get_file_content(
  File "python3.9/site-packages/python_inspector/utils_pypi.py", line 1660, in get_file_content
    _headers, content = get_remote_file_content(
  File "python3.9/site-packages/python_inspector/utils_pypi.py", line 1736, in get_remote_file_content
    with stream as response:
AttributeError: __enter__
```

See https://github.com/nexB/python-inspector/blob/main/src/python_inspector/utils_pypi.py#L1736
I don't think this is the proper way to use the streaming feature of requests.
https://requests.readthedocs.io/en/latest/user/advanced/#streaming-requests

**Comment by tdruez** [comment]
This is actually happening with an older version of request.
`pip install requests==2.14.2`

This requirements needs to be updated https://github.com/nexB/python-inspector/blob/main/setup.cfg#L66
