### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hidden'

### ISSUE THREAD

**Issue by tdruez** [nexB/python-inspector#54]
Clean install on Python 3.9 following the README docs:

```
$ pip install git+https://github.com/nexB/python-inspector
$ python-inspector --help

Traceback (most recent call last):
  File "/Volumes/nexB/repos/dejacode/bin/python-inspector", line 5, in <module>
    from python_inspector.resolve_cli import resolve_dependencies
  File "/Volumes/nexB/repos/dejacode/lib/python3.9/site-packages/python_inspector/resolve_cli.py", line 144, in <module>
    def resolve_dependencies(
  File "/Volumes/nexB/repos/dejacode/lib/python3.9/site-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/Volumes/nexB/repos/dejacode/lib/python3.9/site-packages/click/core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'
```

It seems that the click argument `hidden` is used in the cli but was not available in older versions of click:

```
$ pip show click
Name: click
Version: 6.7

$ pip install click==8.1.3
$ python-inspector --help
Usage: python-inspector [OPTIONS]
.....
```

The min requirement in the setup.py needs to be updated:https://github.com/nexB/python-inspector/blob/main/setup.cfg#L58

**Comment by pombredanne** [comment]
See also https://github.com/nexB/python-inspector/pull/57#discussion_r946783679
