### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by mnonnenmacher** [nexB/python-inspector#72]
With python-inspector 0.7.0, when running `python-inspector --python-version 310 --json-pdt - --requirement requirements.txt` on [this file](https://github.com/deis/example-python-flask/blob/0773991e36a4c69b121cdb05146d6140347d4065/requirements.txt) I get this error:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/python-inspector", line 8, in <module>
    sys.exit(resolve_dependencies())
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/python_inspector/resolve_cli.py", line 363, in resolve_dependencies
    requirements, resolved_dependencies, purls = resolve(
  File "/home/user/.local/lib/python3.8/site-packages/python_inspector/resolve_cli.py", line 453, in resolve
    resolved_dependencies, packages = get_resolved_dependencies(
TypeError: cannot unpack non-iterable NoneType object
```

The same happens with `python-inspector --python-version 27 --json - --setup-py setup.py` and [this file](https://github.com/spdx/tools-python/blob/a48022e65a8897d0e4f2e93d8e53695d2c13ea23/setup.py).

**Comment by TG1999** [comment]
[72.json.txt](https://github.com/nexB/python-inspector/files/9675560/72.json.txt) @mnonnenmacher I was not able to reproduce this error for requirements.txt, uploading the result here

**Comment by TG1999** [comment]
@mnonnenmacher I ran the command with the verbose flag like this `python-inspector --python-version 27 --json - --setup-py setup.py` and it threw this error `Exception('Unable to collect setup.py dependencies securely')`, then I ran it with the insecure flag  like this `python-inspector --python-version 27 --json - --setup-py setup-1.py --analyze-setup-py-insecurely` and got this 
[72-setup-py.json.txt](https://github.com/nexB/python-inspector/files/9675642/72-setup-py.json.txt)

**Comment by mnonnenmacher** [comment]
@TG1999 Thanks, that works for me as well. I think it would be great if the tool would print a meaningful error message also without the `--verbose` flag.

**Comment by pombredanne** [comment]
> I think it would be great if the tool would print a meaningful error message also without the --verbose flag.

@mnonnenmacher we can have an issue to track this if you want.

**Comment by mnonnenmacher** [comment]
@pombredanne Yes, that would be nice, I think that would be a better UX.
