### ISSUE TITLE
Python inspector cannot resolve azure-devops dependency

### ISSUE THREAD

**Issue by nnobelis** [nexB/python-inspector#78]
I have the following requirement.txt file:
```
azure-devops
azure-storage-blob
click
```

If I run:
`python-inspector --python-version 310 --json-pdt - --requirement requirements.txt   --verbose`

it crashes:
```
Resolving dependencies...
Using netrc file /home/XXX/.netrc
direct_dependencies:
 DependentPackage(purl='pkg:pypi/azure-devops', extracted_requirement='azure-devops', scope='install')
 DependentPackage(purl='pkg:pypi/azure-storage-blob', extracted_requirement='azure-storage-blob', scope='install')
 DependentPackage(purl='pkg:pypi/click', extracted_requirement='click', scope='install')
environment: Environment(python_version='310', operating_system='linux')
repos:
 PypiSimpleRepository(index_url='https://pypi.org/simple', credentials=None)
ResolutionImpossible([RequirementInformation(requirement=<Requirement('azure-devops')>, parent=None)])
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/python-inspector", line 8, in <module>
    sys.exit(resolve_dependencies())
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/python_inspector/resolve_cli.py", line 389, in resolve_dependencies
    resolved_dependencies, purls = resolve(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/python_inspector/resolve_cli.py", line 472, in resolve
    resolved_dependencies, packages = get_resolved_dependencies(
TypeError: cannot unpack non-iterable NoneType object
```

If I replace the first line with 
`azure-devops==6.0.0b4`

it is successful.

Why a version is required for azure-devops and not the other ones ?

Also for information, here was the result found with pipdeptree :

![image](https://user-images.githubusercontent.com/66427221/194320031-35d6d3a6-4112-4251-b98b-f9a6339d691b.png)

Why pipdeptree  found the version b2 when the version b4 was available ?

**Comment by TG1999** [comment]
@nnobelis please check https://pypi.org/project/python-inspector/0.8.2/ and let us know if the issue persists

**Comment by nnobelis** [comment]
Thanks. I can confirm the bug is now fixed !
